Give a helpful error message when trying to import a github_branch that does not exist (#734)
* Add tests for importing github_branch

- check importing a branch that exists
- check error message when importing a branch that does not exist

* Add error message for importing github_branch

There was no error message if the branch the user was trying to import
did not exist on GitHub, so the user got the default terraform error:

    Error: nil entry in ImportState results. This is always a bug with
    the resource that is being imported. Please report this as
    a bug to Terraform.

The new error message is:

    Error: Repository tftest does not have a branch named nosuchbranch.